### ISSUE TITLE
Create a test scenario to check if agent starts successfully (if pnpm run works as expected and you can build, run and exit Eliza properly)

### ISSUE THREAD

**Issue by TimKozak** [Sifchain/sa-eliza#86]

**Comment by jzvikart** [comment]
The smoke test in CI/CD seems to be mostly OK, it actually fails on the very last step where "exit" apparently does not terminate the session cleanly.

I cannot reproduce it on my machine, so it's probably environment-specific.

There are also some C code compilation warnings, part of it probably due to differences in versions that are not properly managed (build tools, external libraries, header files, etc.) I'm not getting those warnings on my machine, either.

@monilpat Do we consider this as "good enough" to propose an upstream PR?

**Comment by monilpat** [comment]
Got it - thanks for clarifying. 

I understand re env difference. 

Got it re C warnings. 

I would consider this good enough to propose upstream. But I would recommend looking into the exit or removing it from the test and adding in the exit check once you can get it working as a follow up on that PR. 

Thanks for working on this :)

**Comment by jzvikart** [comment]
Well, "exit" is pretty much everything this test does so removing it would be kind of pointless. Also, this test is really the minimal viable scenario that forms the baseline of every subsequent integration/e2e test. As I mentioned, the point of test is to show us problems that were not visible before so that we could start fixing them, and this is exactly what is happening here.

I could invest some effort and try to fix the problem, but it's unclear to me how much time we want to spend on it.

**Comment by jzvikart** [comment]
Done.
